#pragma once
#include <glm/glm.hpp>

/**
 * @brief Struct representing the state of a tire based on slip ratio and slip angle.
 *
 * This struct encapsulates the key parameters that describe the behavior of a tire
 * under various conditions, such as acceleration, braking, and cornering. The
 * slip ratio and slip angle are used to compute the forces generated by the tire,
 * which are essential for realistic vehicle physics simulation.
 */
struct TireState
{
	float slipRatio;     ///< slip ratio (Vvar - Vnormal) / max(Vnormal, 0.1f)
	float slipAngle;     ///< slip angle in radians, positive for right slip, negative for left slip
    float adherence;     ///< Vvar / Vnormal
	glm::vec3 force;     ///< lateral and longitudinal forces generated by the tire, in the tire's local coordinate system (x = forward, y = lateral, z = vertical)
};

/**
 * @brief Class responsible for computing the tire state based on input parameters.
 *
 * The TireModel class provides a static method to compute the TireState given
 * the normal velocity, slip velocity, steering angle, and axle angle. This
 * computation is crucial for simulating realistic tire behavior in a vehicle
 * physics system, allowing for accurate handling and response to driver inputs.
 */
class TireModel
{
public:
	/**
	 * @brief Computes the tire state based on the normal velocity, slip velocity, steering angle, and axle angle.
	 * 
	 * \param Vnormal
	 * \param Vvar
	 * \param steerAngle
	 * \param axleAngle
	 * \return 
	 */
    static TireState Compute(float Vnormal, float Vvar, float steerAngle, float axleAngle);
};